name: Release minor version to clojars

on:
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
    uses: ruroru/workflows/.github/workflows/clojars-release-minor.yaml@master
    with:
      lein_compile_profile: "dev"
    secrets:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
      CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
